[package]
name = "codegen"
version = "0.7.0"
edition = "2021"

[dependencies]
darling = "0.20"
syn = { version = "2" }
quote = "1"
proc-macro2 = "1"
proc-macro-crate = "1"
proc-macro-error = "1"
convert_case = "0.6"

examples = { version = "0.4.0", registry = "substrate", path = "../docs/examples" }
type_dispatch = { version = "0.3.0", registry = "substrate", path = "../libs/type_dispatch" }

[dev-dependencies]
arcstr = "1"
serde = { version = "1", features = ["derive"] }
substrate = { version = "<=0.7.0", registry = "substrate", path = "../substrate" }
sky130pdk = { version = "<=0.7.0", registry = "substrate", path = "../pdks/sky130pdk" }
spectre = { version = "<=0.7.0", registry = "substrate", path = "../tools/spectre" }

[lib]
proc-macro = true
