[package]
name = "spectre"
version = "0.3.0"
edition = "2021"

[dependencies]
rust_decimal = "1.31"
rust_decimal_macros = "1.31"
thiserror = "1"
arcstr = { version = "1", features = [ "serde" ] }
psfparser = "0.1"
tera = "1"
lazy_static = "1"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"

cache = { version = "0.2.0", registry = "substrate", path = "../../libs/cache" }
scir = { version = "0.2.0", registry = "substrate", path = "../../libs/scir" }
substrate = { version = "0.3.0", registry = "substrate", path = "../../substrate" }
opacity = { version = "0.1.0", path = "../../libs/opacity", registry = "substrate" }
